/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thinkfastwithjava;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Bayan Mamun ID: 434023821
 */
public class JavaGameForm extends javax.swing.JFrame {
      static  PlayerInfo player; 
      
    /**
     * Creates new form JavaGameForm
     */
    public JavaGameForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        setVisible(true);
        player = new PlayerInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardsPanel = new javax.swing.JPanel();
        welcomeCard = new javax.swing.JPanel();
        ThinkFastWithJava = new javax.swing.JLabel();
        javaLogo = new javax.swing.JLabel();
        welcome = new javax.swing.JButton();
        background1 = new javax.swing.JLabel();
        MainMenu = new javax.swing.JPanel();
        MainMenuText = new javax.swing.JLabel();
        HavePastRecord = new javax.swing.JButton();
        NewPlayerBitton = new javax.swing.JButton();
        Help = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        background2 = new javax.swing.JLabel();
        SignInCard = new javax.swing.JPanel();
        PastName = new javax.swing.JLabel();
        PastNameCon = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        Start = new javax.swing.JButton();
        Exit1 = new javax.swing.JButton();
        Help3 = new javax.swing.JButton();
        messageNameError = new javax.swing.JLabel();
        background4 = new javax.swing.JLabel();
        SignUpCard = new javax.swing.JPanel();
        SignUp = new javax.swing.JLabel();
        PastNameCon1 = new javax.swing.JLabel();
        Help4 = new javax.swing.JButton();
        Exit2 = new javax.swing.JButton();
        Name1 = new javax.swing.JTextField();
        Start1 = new javax.swing.JButton();
        InsertRecord = new javax.swing.JButton();
        messageNameError1 = new javax.swing.JLabel();
        messageNameError2 = new javax.swing.JLabel();
        messageNameError3 = new javax.swing.JLabel();
        background5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Think Fast With Java");
        setBackground(new java.awt.Color(255, 242, 203));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("A Yummy Apology", 0, 18)); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(540, 600));

        cardsPanel.setLayout(new java.awt.CardLayout());

        welcomeCard.setLayout(null);

        ThinkFastWithJava.setFont(new java.awt.Font("Timotheos", 0, 62)); // NOI18N
        ThinkFastWithJava.setForeground(new java.awt.Color(102, 91, 84));
        ThinkFastWithJava.setText("Think Fast With");
        welcomeCard.add(ThinkFastWithJava);
        ThinkFastWithJava.setBounds(40, 40, 460, 88);

        javaLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thinkfastwithjava/java-logo-vector-c.png"))); // NOI18N
        welcomeCard.add(javaLogo);
        javaLogo.setBounds(140, 100, 220, 320);

        welcome.setBackground(new java.awt.Color(236, 236, 236));
        welcome.setFont(new java.awt.Font("Timotheos", 0, 24)); // NOI18N
        welcome.setForeground(new java.awt.Color(189, 141, 125));
        welcome.setText("Continue");
        welcome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                welcomeActionPerformed(evt);
            }
        });
        welcomeCard.add(welcome);
        welcome.setBounds(60, 440, 370, 50);

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thinkfastwithjava/sea_of_clouds-wallpaper-960x600.jpg"))); // NOI18N
        welcomeCard.add(background1);
        background1.setBounds(0, 0, 540, 560);

        cardsPanel.add(welcomeCard, "card6");

        MainMenu.setLayout(null);

        MainMenuText.setFont(new java.awt.Font("Timotheos", 0, 70)); // NOI18N
        MainMenuText.setForeground(new java.awt.Color(102, 91, 84));
        MainMenuText.setText("Main Menu");
        MainMenu.add(MainMenuText);
        MainMenuText.setBounds(90, 80, 370, 99);

        HavePastRecord.setBackground(new java.awt.Color(236, 236, 236));
        HavePastRecord.setFont(new java.awt.Font("Timotheos", 0, 24)); // NOI18N
        HavePastRecord.setForeground(new java.awt.Color(189, 141, 125));
        HavePastRecord.setText("Have Past Record");
        HavePastRecord.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        HavePastRecord.setVerifyInputWhenFocusTarget(false);
        HavePastRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HavePastRecordActionPerformed(evt);
            }
        });
        MainMenu.add(HavePastRecord);
        HavePastRecord.setBounds(120, 200, 290, 50);

        NewPlayerBitton.setBackground(new java.awt.Color(236, 236, 236));
        NewPlayerBitton.setFont(new java.awt.Font("Timotheos", 0, 24)); // NOI18N
        NewPlayerBitton.setForeground(new java.awt.Color(189, 141, 125));
        NewPlayerBitton.setText("New Player");
        NewPlayerBitton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewPlayerBittonActionPerformed(evt);
            }
        });
        MainMenu.add(NewPlayerBitton);
        NewPlayerBitton.setBounds(120, 270, 290, 50);

        Help.setBackground(new java.awt.Color(236, 236, 236));
        Help.setFont(new java.awt.Font("Timotheos", 0, 24)); // NOI18N
        Help.setForeground(new java.awt.Color(189, 141, 125));
        Help.setText("?");
        Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpActionPerformed(evt);
            }
        });
        MainMenu.add(Help);
        Help.setBounds(230, 410, 60, 50);

        Exit.setBackground(new java.awt.Color(236, 236, 236));
        Exit.setFont(new java.awt.Font("Timotheos", 0, 24)); // NOI18N
        Exit.setForeground(new java.awt.Color(189, 141, 125));
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        MainMenu.add(Exit);
        Exit.setBounds(120, 340, 290, 50);

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thinkfastwithjava/sea_of_clouds-wallpaper-960x600.jpg"))); // NOI18N
        MainMenu.add(background2);
        background2.setBounds(0, 0, 540, 560);

        cardsPanel.add(MainMenu, "BackToMenu");
        cardsPanel.add(MainMenu, "welcome");
        MainMenu.getAccessibleContext().setAccessibleDescription("");

        SignInCard.setBackground(new java.awt.Color(255, 255, 255));
        SignInCard.setLayout(null);
        SignInCard.show(false);

        PastName.setFont(new java.awt.Font("Timotheos", 0, 70)); // NOI18N
        PastName.setForeground(new java.awt.Color(102, 91, 84));
        PastName.setText("Sign in:");
        SignInCard.add(PastName);
        PastName.setBounds(60, 150, 260, 90);

        PastNameCon.setFont(new java.awt.Font("Timotheos", 0, 20)); // NOI18N
        PastNameCon.setForeground(new java.awt.Color(172, 122, 105));
        PastNameCon.setText("search for your record to start playing");
        SignInCard.add(PastNameCon);
        PastNameCon.setBounds(60, 250, 430, 28);

        Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        SignInCard.add(Name);
        Name.setBounds(110, 290, 300, 40);

        Start.setBackground(new java.awt.Color(189, 141, 125));
        Start.setFont(new java.awt.Font("Timotheos", 0, 18)); // NOI18N
        Start.setForeground(new java.awt.Color(255, 255, 255));
        Start.setText("Start Playing");
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });
        SignInCard.add(Start);
        Start.setBounds(180, 400, 160, 60);

        Exit1.setBackground(new java.awt.Color(236, 236, 236));
        Exit1.setFont(new java.awt.Font("Timotheos", 0, 36)); // NOI18N
        Exit1.setForeground(new java.awt.Color(153, 0, 0));
        Exit1.setText("X");
        Exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit1ActionPerformed(evt);
            }
        });
        SignInCard.add(Exit1);
        Exit1.setBounds(430, 20, 60, 50);

        Help3.setBackground(new java.awt.Color(236, 236, 236));
        Help3.setFont(new java.awt.Font("Timotheos", 0, 36)); // NOI18N
        Help3.setForeground(new java.awt.Color(153, 0, 0));
        Help3.setText("?");
        Help3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Help3ActionPerformed(evt);
            }
        });
        SignInCard.add(Help3);
        Help3.setBounds(350, 20, 70, 50);

        messageNameError.setFont(new java.awt.Font("Timotheos", 0, 18)); // NOI18N
        messageNameError.setForeground(new java.awt.Color(255, 0, 0));
        messageNameError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messageNameError.setText("<html><p style=\"text-align: center\">OOps!! it seems you foregot to write your name <br/>or it is not actually your name</p></html>");
        messageNameError.setVisible(false);
        SignInCard.add(messageNameError);
        messageNameError.setBounds(60, 340, 410, 50);

        background4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thinkfastwithjava/sea_of_clouds-wallpaper-960x600.jpg"))); // NOI18N
        SignInCard.add(background4);
        background4.setBounds(0, 0, 540, 560);

        cardsPanel.add(SignInCard, "HavePastRecord");

        SignUpCard.setLayout(null);

        SignUp.setFont(new java.awt.Font("Timotheos", 0, 70)); // NOI18N
        SignUp.setForeground(new java.awt.Color(102, 91, 84));
        SignUp.setText("Sign up:");
        SignUpCard.add(SignUp);
        SignUp.setBounds(60, 150, 280, 90);

        PastNameCon1.setFont(new java.awt.Font("Timotheos", 0, 20)); // NOI18N
        PastNameCon1.setForeground(new java.awt.Color(172, 122, 105));
        PastNameCon1.setText("Enter Cool Name to start Playing");
        SignUpCard.add(PastNameCon1);
        PastNameCon1.setBounds(60, 250, 410, 28);

        Help4.setBackground(new java.awt.Color(236, 236, 236));
        Help4.setFont(new java.awt.Font("Timotheos", 0, 36)); // NOI18N
        Help4.setForeground(new java.awt.Color(153, 0, 0));
        Help4.setText("?");
        Help4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Help4ActionPerformed(evt);
            }
        });
        SignUpCard.add(Help4);
        Help4.setBounds(350, 20, 70, 50);

        Exit2.setBackground(new java.awt.Color(236, 236, 236));
        Exit2.setFont(new java.awt.Font("Timotheos", 0, 36)); // NOI18N
        Exit2.setForeground(new java.awt.Color(153, 0, 0));
        Exit2.setText("X");
        Exit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit2ActionPerformed(evt);
            }
        });
        SignUpCard.add(Exit2);
        Exit2.setBounds(430, 20, 60, 50);

        Name1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Name1ActionPerformed(evt);
            }
        });
        SignUpCard.add(Name1);
        Name1.setBounds(110, 290, 300, 40);

        Start1.setBackground(new java.awt.Color(189, 141, 125));
        Start1.setFont(new java.awt.Font("Timotheos", 0, 14)); // NOI18N
        Start1.setForeground(new java.awt.Color(255, 255, 255));
        Start1.setText("Start Playing");
        Start1.setEnabled(false);
        Start1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Start1ActionPerformed(evt);
            }
        });
        SignUpCard.add(Start1);
        Start1.setBounds(80, 400, 160, 60);

        InsertRecord.setBackground(new java.awt.Color(189, 141, 125));
        InsertRecord.setFont(new java.awt.Font("Timotheos", 0, 14)); // NOI18N
        InsertRecord.setForeground(new java.awt.Color(255, 255, 255));
        InsertRecord.setText("Insert My Record");
        InsertRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertRecordActionPerformed(evt);
            }
        });
        SignUpCard.add(InsertRecord);
        InsertRecord.setBounds(270, 400, 160, 60);

        messageNameError1.setFont(new java.awt.Font("Timotheos", 0, 18)); // NOI18N
        messageNameError1.setForeground(new java.awt.Color(255, 0, 0));
        messageNameError1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messageNameError1.setText("OOps!!  It seems you forgot to enter your Name @_@");
        messageNameError1.setVisible(false);
        SignUpCard.add(messageNameError1);
        messageNameError1.setBounds(30, 340, 480, 50);

        messageNameError2.setFont(new java.awt.Font("Timotheos", 0, 18)); // NOI18N
        messageNameError2.setForeground(new java.awt.Color(255, 0, 0));
        messageNameError2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messageNameError2.setText("It Seems this in not your name $_$");
        messageNameError2.setVisible(false);
        SignUpCard.add(messageNameError2);
        messageNameError2.setBounds(90, 340, 340, 50);

        messageNameError3.setFont(new java.awt.Font("Timotheos", 0, 18)); // NOI18N
        messageNameError3.setForeground(new java.awt.Color(0, 153, 0));
        messageNameError3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messageNameError3.setText("That is The Best Name ever!!");
        messageNameError3.setVisible(false);
        SignUpCard.add(messageNameError3);
        messageNameError3.setBounds(90, 340, 340, 50);

        background5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thinkfastwithjava/sea_of_clouds-wallpaper-960x600.jpg"))); // NOI18N
        SignUpCard.add(background5);
        background5.setBounds(0, 0, 540, 560);

        cardsPanel.add(SignUpCard, "NewPlayerBitton");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * game close operation
     */
    public void close(){
           WindowEvent winClosingEvent =  new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
           Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
       }
    
    /**
     * 
     * @param sign up 
     */
    private void NewPlayerBittonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewPlayerBittonActionPerformed
        String newRecord = "NewPlayerBitton";
        CardLayout layout = (CardLayout)this.cardsPanel.getLayout();
        layout.show(cardsPanel, newRecord);
        this.Name.setText("");
    }//GEN-LAST:event_NewPlayerBittonActionPerformed
     /**
      * 
      * @param sign in 
      */
    private void HavePastRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HavePastRecordActionPerformed
        String haveRecord = "HavePastRecord";
        CardLayout layout = (CardLayout)this.cardsPanel.getLayout();
        layout.show(cardsPanel, haveRecord);
        this.Name.setText("");
    }//GEN-LAST:event_HavePastRecordActionPerformed
      /**
       * 
       * @param tutorial 
       */
    private void HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpActionPerformed
             JavaGameFrame2 frame2 = new JavaGameFrame2();
             frame2.setVisible(true);
          try {
              player.readInFile();
          } catch (IOException ex) {
              Logger.getLogger(JavaGameForm.class.getName()).log(Level.SEVERE, null, ex);
          }

    }//GEN-LAST:event_HelpActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        
    }//GEN-LAST:event_NameActionPerformed

    private void Name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Name1ActionPerformed
        
    }//GEN-LAST:event_Name1ActionPerformed
       /**
        * 
        * @param start game after sign in 
        */
    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed

       player.setPlayerName(this.Name.getText());
       if(player.isPlayerExist(this.Name.getText()) && this.Name.getText() != null){                   
           WelcomePlayer welcome = new WelcomePlayer();
           welcome.setVisible(true);
           welcome.ReallyNew.setVisible(false);
           WelcomePlayer.PlayerName.setText(this.Name.getText());
           welcome.DeleteRecord.setVisible(true);
           player = PlayerInfo.loadPlayerInfo(this.Name.getText()); 
           if(player.levels.levelNum==0){
             welcome.ResetPoints.setVisible(true);
             welcome.ReallyExist.setVisible(false);
             welcome.DeleteRecord.setVisible(true);
             welcome.ScoreText.setVisible(false);
             welcome.LevelText.setVisible(false);
             WelcomePlayer.ExistPlayerInfo1.setVisible(false);
             WelcomePlayer.ExistPlayerInfo2.setVisible(false);
             welcome.AllLevelsFinished.setVisible(true);
             welcome.AreYouReady.setVisible(false);             
           }
           WelcomePlayer.ExistPlayerInfo1.setText(player.printScore());//your score 
           WelcomePlayer.ExistPlayerInfo2.setText(player.printLevelNum());//you are at level
           close();
       }else if(!(player.isPlayerExist(this.Name.getText())) || this.Name.getText() == null){
           messageNameError.setVisible(true);
       }
       
    }//GEN-LAST:event_StartActionPerformed
          
    /**
     * 
     * @param welcoming 
     */
    private void welcomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_welcomeActionPerformed
                 
        String welcome = "welcome";
        CardLayout layout = (CardLayout)this.cardsPanel.getLayout();
        layout.show(cardsPanel, welcome);
        
    }//GEN-LAST:event_welcomeActionPerformed
      /**
       * 
       * @param tutorial 
       */
    private void Help3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Help3ActionPerformed
        JavaGameFrame2 frame2 = new JavaGameFrame2();
             frame2.setVisible(true);
             try {
              player.readInFile();
          } catch (IOException ex) {
              Logger.getLogger(JavaGameForm.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_Help3ActionPerformed
       /**
        * 
        * @param game close operation 
        */
    private void Exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit1ActionPerformed
        ExitFrame exit = new  ExitFrame();
        exit.setVisible(true);
    }//GEN-LAST:event_Exit1ActionPerformed
      
    /**
     * 
     * @param tutorial 
     */
    private void Help4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Help4ActionPerformed
        JavaGameFrame2 frame2 = new JavaGameFrame2();
             frame2.setVisible(true);
             try {
              player.readInFile();
          } catch (IOException ex) {
              Logger.getLogger(JavaGameForm.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_Help4ActionPerformed
      
    /**
     * 
     * @param game close operation 
     */
    private void Exit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit2ActionPerformed
        ExitFrame exit = new  ExitFrame();
        exit.setVisible(true);
    }//GEN-LAST:event_Exit2ActionPerformed
      
    /**
     * 
     * @param game close operation 
     */
    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        ExitFrame exit = new  ExitFrame();
        exit.setVisible(true);
        
    }//GEN-LAST:event_ExitActionPerformed
     /**
      * 
      * @param start game after sign up
      */
    private void Start1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Start1ActionPerformed

               close();
               WelcomePlayer welcome = new WelcomePlayer();
               welcome.setVisible(true);
               welcome.ReallyExist.setVisible(false);
               WelcomePlayer.PlayerName.setText(Name1.getText());
               player=PlayerInfo.loadPlayerInfo(Name1.getText());
               WelcomePlayer.ExistPlayerInfo1.setText(player.printScore());//your score 
               WelcomePlayer.ExistPlayerInfo2.setText(player.printLevelNum());//you are at level
               welcome.ResetPoints.setVisible(false);
                      
    }//GEN-LAST:event_Start1ActionPerformed
        /**
         * 
         * @param insert new player into database 
         */
    private void InsertRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertRecordActionPerformed

                  if(Name1.getText().equals("")){
                     messageNameError1.setVisible(true);
                     messageNameError2.setVisible(false);
                     messageNameError3.setVisible(false);
                    }
                     else if(player.isPlayerExist(Name1.getText())){
                        messageNameError2.setVisible(true); 
                        messageNameError1.setVisible(false);
                        messageNameError3.setVisible(false);
                 }                          
             else{
                         
                messageNameError1.setVisible(false);
                messageNameError2.setVisible(false);
                messageNameError3.setVisible(true);
                player.savePlayerInfo(Name1.getText());
                InsertRecord.setEnabled(false);
                Start1.setEnabled(true);
            }                 
    }//GEN-LAST:event_InsertRecordActionPerformed
         
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaGameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaGameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaGameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaGameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaGameForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JButton Exit1;
    private javax.swing.JButton Exit2;
    private javax.swing.JButton HavePastRecord;
    private javax.swing.JButton Help;
    private javax.swing.JButton Help3;
    private javax.swing.JButton Help4;
    private javax.swing.JButton InsertRecord;
    protected javax.swing.JPanel MainMenu;
    private javax.swing.JLabel MainMenuText;
    protected static javax.swing.JTextField Name;
    protected static javax.swing.JTextField Name1;
    private javax.swing.JButton NewPlayerBitton;
    private javax.swing.JLabel PastName;
    private javax.swing.JLabel PastNameCon;
    private javax.swing.JLabel PastNameCon1;
    private transient javax.swing.JPanel SignInCard;
    private javax.swing.JLabel SignUp;
    private javax.swing.JPanel SignUpCard;
    private javax.swing.JButton Start;
    private javax.swing.JButton Start1;
    private javax.swing.JLabel ThinkFastWithJava;
    private javax.swing.JLabel background1;
    private javax.swing.JLabel background2;
    private javax.swing.JLabel background4;
    private javax.swing.JLabel background5;
    protected javax.swing.JPanel cardsPanel;
    private javax.swing.JLabel javaLogo;
    private javax.swing.JLabel messageNameError;
    private javax.swing.JLabel messageNameError1;
    private javax.swing.JLabel messageNameError2;
    private javax.swing.JLabel messageNameError3;
    private javax.swing.JButton welcome;
    protected javax.swing.JPanel welcomeCard;
    // End of variables declaration//GEN-END:variables
}
