/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thinkfastwithjava;

import java.awt.CardLayout;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author Bayan Mamun ID: 434023821
 */
public class JavaGameFrame2 extends javax.swing.JFrame {

    /**
     * Creates new form JavaGameFrame2
     */
    public JavaGameFrame2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardsPanel2 = new javax.swing.JPanel();
        TutorialCard = new javax.swing.JPanel();
        tutorialText = new javax.swing.JScrollPane();
        TutorialFromFile = new javax.swing.JTextArea();
        Exit = new javax.swing.JButton();
        Tutorial = new javax.swing.JLabel();
        background3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(560, 600));

        cardsPanel2.setLayout(new java.awt.CardLayout());

        TutorialCard.setLayout(null);

        tutorialText.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        tutorialText.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        tutorialText.setEnabled(false);
        tutorialText.setWheelScrollingEnabled(false);
        tutorialText.setAlignmentY(javax.swing.JTextArea.RIGHT_ALIGNMENT);

        TutorialFromFile.setEditable(false);
        TutorialFromFile.setBackground(new java.awt.Color(210, 228, 255));
        TutorialFromFile.setColumns(20);
        TutorialFromFile.setFont(new java.awt.Font("Tempus Sans ITC", 0, 16)); // NOI18N
        TutorialFromFile.setLineWrap(true);
        TutorialFromFile.setRows(17);
        TutorialFromFile.setAlignmentX(5.5F);
        TutorialFromFile.setBorder(null);
        TutorialFromFile.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TutorialFromFile.setEnabled(false);
        TutorialFromFile.setAlignmentY(javax.swing.JTextArea.RIGHT_ALIGNMENT);
        tutorialText.setViewportView(TutorialFromFile);

        TutorialCard.add(tutorialText);
        tutorialText.setBounds(46, 101, 470, 400);

        Exit.setBackground(new java.awt.Color(236, 236, 236));
        Exit.setFont(new java.awt.Font("Timotheos", 0, 36)); // NOI18N
        Exit.setForeground(new java.awt.Color(153, 0, 0));
        Exit.setText("X");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        TutorialCard.add(Exit);
        Exit.setBounds(460, 20, 60, 50);

        Tutorial.setFont(new java.awt.Font("Timotheos", 0, 55)); // NOI18N
        Tutorial.setForeground(new java.awt.Color(102, 91, 84));
        Tutorial.setText("Tutorial");
        TutorialCard.add(Tutorial);
        Tutorial.setBounds(160, 20, 230, 70);

        background3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thinkfastwithjava/sea_of_clouds-wallpaper-960x600.jpg"))); // NOI18N
        TutorialCard.add(background3);
        background3.setBounds(0, 0, 580, 570);

        cardsPanel2.add(TutorialCard, "Help");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardsPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardsPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
        /**
         * 
         * @param close tutorial operation 
         */
    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        dispose();
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaGameFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaGameFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaGameFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaGameFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaGameFrame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JLabel Tutorial;
    private javax.swing.JPanel TutorialCard;
    protected static javax.swing.JTextArea TutorialFromFile;
    private javax.swing.JLabel background3;
    private javax.swing.JPanel cardsPanel2;
    protected javax.swing.JScrollPane tutorialText;
    // End of variables declaration//GEN-END:variables
}
