/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thinkfastwithjava;

import java.awt.CardLayout;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import static thinkfastwithjava.JavaGameForm.player;

/**
 *
 * @author Bayan Mamun ID: 434023821
 */
public class NewJFrame extends javax.swing.JFrame {
private int  m=1,s=59;
public Timer timer;
Questions q;
Vector <Questions> questions ;
String timeOut = "Out";
    /**
     * Creates new form NewJFrame
     */


    public NewJFrame() {
        initComponents();
       this.setLocationRelativeTo(null);
      q = new Questions(); 
      boolean nextLevel;
     questions = Questions.loadQuestionInfo(JavaGameForm.player.levels.levelNum);
    timer= new Timer(1000,new stsrtshow()); 
    }
    
    /**
     *  timer 
     */
    private class stsrtshow implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
         if (s!=0&&s<=59){
             s--;
            String sec=(s<10?"0":"")+s;
             Seconds.setText(""+sec);
         }
         if(m>=1&&s==0){
             m--;
             String mu=(m<10?"0":"")+m;
             s=59;
             Seconds.setText(""+s);
             minutes.setText(""+mu);}
         
         if(m==0&&s==0) {
             timer.stop();
             Answer1.setEnabled(false);
             Answer2.setEnabled(false);
             AnswerPlace.setVisible(false);
             AnswerPlace2.setVisible(false);
             TimeOut.setVisible(true);             
                 
         }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    /**
     *   close frame operation
     */
    public void close(){
           WindowEvent winClosingEvent =  new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
           Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
       }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardsPanel2 = new javax.swing.JPanel();
        TimerAndLevelPanel = new javax.swing.JPanel();
        Time = new javax.swing.JLabel();
        minutes = new javax.swing.JLabel();
        Seconds = new javax.swing.JLabel();
        simicolon = new javax.swing.JLabel();
        hourglassIcon = new javax.swing.JLabel();
        LevelNum = new javax.swing.JLabel();
        score1 = new javax.swing.JLabel();
        Level = new javax.swing.JLabel();
        score = new javax.swing.JLabel();
        Question = new javax.swing.JLabel();
        AnswerPlace = new javax.swing.JLabel();
        AnswerPlace2 = new javax.swing.JLabel();
        TimeOut = new javax.swing.JLabel();
        Exit = new javax.swing.JButton();
        Pause = new javax.swing.JButton();
        Resume = new javax.swing.JButton();
        NextQuestion = new javax.swing.JButton();
        Answer1 = new javax.swing.JTextField();
        Answer2 = new javax.swing.JTextField();
        background6 = new javax.swing.JLabel();
        ReportCard = new javax.swing.JPanel();
        LevelFinished = new javax.swing.JLabel();
        playerName = new javax.swing.JLabel();
        NextLavel = new javax.swing.JButton();
        PlayerScore = new javax.swing.JLabel();
        scoreLoad = new javax.swing.JLabel();
        levelText = new javax.swing.JLabel();
        levelNumLoad = new javax.swing.JLabel();
        resetText = new javax.swing.JLabel();
        GoodPoints = new javax.swing.JLabel();
        Again = new javax.swing.JButton();
        Exit1 = new javax.swing.JButton();
        ResetPoints = new javax.swing.JButton();
        background7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Level 1");
        setResizable(false);
        setSize(new java.awt.Dimension(540, 600));

        cardsPanel2.setLayout(new java.awt.CardLayout());

        TimerAndLevelPanel.setLayout(null);

        Time.setFont(new java.awt.Font("Timotheos", 0, 18)); // NOI18N
        Time.setForeground(new java.awt.Color(153, 0, 0));
        Time.setText("Time");
        TimerAndLevelPanel.add(Time);
        Time.setBounds(90, 20, 50, 30);

        minutes.setFont(new java.awt.Font("Timotheos", 0, 18)); // NOI18N
        minutes.setForeground(new java.awt.Color(110, 125, 167));
        minutes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        minutes.setText("01");
        TimerAndLevelPanel.add(minutes);
        minutes.setBounds(140, 20, 50, 34);

        Seconds.setFont(new java.awt.Font("Timotheos", 0, 18)); // NOI18N
        Seconds.setForeground(new java.awt.Color(110, 125, 167));
        Seconds.setText("59");
        TimerAndLevelPanel.add(Seconds);
        Seconds.setBounds(220, 10, 60, 50);

        simicolon.setFont(new java.awt.Font("Timotheos", 0, 18)); // NOI18N
        simicolon.setForeground(new java.awt.Color(110, 125, 167));
        simicolon.setText(":");
        TimerAndLevelPanel.add(simicolon);
        simicolon.setBounds(200, 10, 20, 42);

        hourglassIcon.setForeground(new java.awt.Color(189, 141, 125));
        hourglassIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thinkfastwithjava/sending.gif"))); // NOI18N
        TimerAndLevelPanel.add(hourglassIcon);
        hourglassIcon.setBounds(10, 10, 80, 90);

        LevelNum.setFont(new java.awt.Font("Timotheos", 0, 18)); // NOI18N
        LevelNum.setForeground(new java.awt.Color(153, 0, 0));
        TimerAndLevelPanel.add(LevelNum);
        LevelNum.setBounds(320, 60, 70, 30);

        score1.setFont(new java.awt.Font("Timotheos", 0, 18)); // NOI18N
        score1.setForeground(new java.awt.Color(153, 0, 0));
        score1.setText("Score");
        TimerAndLevelPanel.add(score1);
        score1.setBounds(90, 60, 60, 24);

        Level.setFont(new java.awt.Font("Timotheos", 0, 18)); // NOI18N
        Level.setForeground(new java.awt.Color(153, 0, 0));
        Level.setText("Level: ");
        TimerAndLevelPanel.add(Level);
        Level.setBounds(260, 60, 60, 24);

        score.setFont(new java.awt.Font("Timotheos", 0, 18)); // NOI18N
        score.setForeground(new java.awt.Color(110, 125, 167));
        score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score.setText("0");
        TimerAndLevelPanel.add(score);
        score.setBounds(150, 60, 50, 30);

        Question.setBackground(new java.awt.Color(225, 225, 225));
        Question.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(110, 125, 167), 3, true));
        Question.setOpaque(true);
        TimerAndLevelPanel.add(Question);
        Question.setBounds(30, 110, 470, 250);

        AnswerPlace.setFont(new java.awt.Font("Timotheos", 0, 24)); // NOI18N
        AnswerPlace.setForeground(new java.awt.Color(0, 153, 255));
        AnswerPlace.setText("what is wrong?");
        TimerAndLevelPanel.add(AnswerPlace);
        AnswerPlace.setBounds(40, 380, 470, 32);

        AnswerPlace2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        AnswerPlace2.setForeground(new java.awt.Color(0, 102, 204));
        AnswerPlace2.setText("Complete  code?");
        TimerAndLevelPanel.add(AnswerPlace2);
        AnswerPlace2.setBounds(40, 390, 420, 29);

        TimeOut.setFont(new java.awt.Font("Timotheos", 0, 24)); // NOI18N
        TimeOut.setForeground(new java.awt.Color(196, 0, 0));
        TimeOut.setText("Time Out .. you can't answer anymore");
        TimeOut.setVisible(false);
        TimerAndLevelPanel.add(TimeOut);
        TimeOut.setBounds(50, 370, 460, 60);

        Exit.setBackground(new java.awt.Color(236, 236, 236));
        Exit.setFont(new java.awt.Font("Timotheos", 0, 36)); // NOI18N
        Exit.setForeground(new java.awt.Color(153, 0, 0));
        Exit.setText("X");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        TimerAndLevelPanel.add(Exit);
        Exit.setBounds(470, 10, 60, 50);

        Pause.setBackground(new java.awt.Color(236, 236, 236));
        Pause.setFont(new java.awt.Font("Timotheos", 1, 36)); // NOI18N
        Pause.setForeground(new java.awt.Color(153, 0, 0));
        Pause.setText("II");
        Pause.setToolTipText("");
        Pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PauseActionPerformed(evt);
            }
        });
        TimerAndLevelPanel.add(Pause);
        Pause.setBounds(400, 10, 60, 50);

        Resume.setBackground(new java.awt.Color(236, 236, 236));
        Resume.setFont(new java.awt.Font("Timotheos", 1, 48)); // NOI18N
        Resume.setForeground(new java.awt.Color(51, 204, 0));
        Resume.setText(">");
        Resume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResumeActionPerformed(evt);
            }
        });
        TimerAndLevelPanel.add(Resume);
        Resume.setBounds(400, 10, 60, 50);

        NextQuestion.setBackground(new java.awt.Color(189, 141, 125));
        NextQuestion.setFont(new java.awt.Font("Timotheos", 0, 18)); // NOI18N
        NextQuestion.setForeground(new java.awt.Color(255, 255, 255));
        NextQuestion.setText("Next Q");
        NextQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextQuestionActionPerformed(evt);
            }
        });
        TimerAndLevelPanel.add(NextQuestion);
        NextQuestion.setBounds(210, 500, 110, 33);

        Answer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Answer1ActionPerformed(evt);
            }
        });
        TimerAndLevelPanel.add(Answer1);
        Answer1.setBounds(290, 430, 180, 40);
        TimerAndLevelPanel.add(Answer2);
        Answer2.setBounds(60, 430, 180, 40);

        background6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thinkfastwithjava/sea_of_clouds-wallpaper-960x600.jpg"))); // NOI18N
        TimerAndLevelPanel.add(background6);
        background6.setBounds(0, 0, 590, 570);

        cardsPanel2.add(TimerAndLevelPanel, "Really");

        ReportCard.setLayout(null);

        LevelFinished.setFont(new java.awt.Font("Timotheos", 0, 40)); // NOI18N
        LevelFinished.setForeground(new java.awt.Color(153, 0, 0));
        LevelFinished.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LevelFinished.setText("Your Performance");
        ReportCard.add(LevelFinished);
        LevelFinished.setBounds(20, 60, 460, 80);

        playerName.setFont(new java.awt.Font("Timotheos", 0, 60)); // NOI18N
        playerName.setForeground(new java.awt.Color(0, 153, 255));
        playerName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReportCard.add(playerName);
        playerName.setBounds(74, 150, 350, 90);

        NextLavel.setBackground(new java.awt.Color(189, 141, 125));
        NextLavel.setFont(new java.awt.Font("Timotheos", 0, 14)); // NOI18N
        NextLavel.setForeground(new java.awt.Color(255, 255, 255));
        NextLavel.setText("Next");
        NextLavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextLavelActionPerformed(evt);
            }
        });
        ReportCard.add(NextLavel);
        NextLavel.setBounds(290, 500, 130, 40);

        PlayerScore.setFont(new java.awt.Font("Timotheos", 0, 24)); // NOI18N
        PlayerScore.setForeground(new java.awt.Color(0, 153, 255));
        PlayerScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReportCard.add(PlayerScore);
        PlayerScore.setBounds(190, 280, 130, 30);

        scoreLoad.setFont(new java.awt.Font("Timotheos", 0, 18)); // NOI18N
        scoreLoad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreLoad.setText("Your Score");
        ReportCard.add(scoreLoad);
        scoreLoad.setBounds(134, 250, 240, 30);

        levelText.setFont(new java.awt.Font("Timotheos", 0, 18)); // NOI18N
        levelText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        levelText.setText("You are at Level:");
        ReportCard.add(levelText);
        levelText.setBounds(160, 340, 190, 21);

        levelNumLoad.setFont(new java.awt.Font("Timotheos", 0, 18)); // NOI18N
        levelNumLoad.setForeground(new java.awt.Color(0, 153, 255));
        levelNumLoad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        levelNumLoad.setToolTipText("");
        ReportCard.add(levelNumLoad);
        levelNumLoad.setBounds(210, 360, 80, 40);

        resetText.setFont(new java.awt.Font("Timotheos", 0, 18)); // NOI18N
        resetText.setForeground(new java.awt.Color(255, 0, 0));
        resetText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resetText.setText("Points to low :'( you should restert The level");
        resetText.setVisible(false);
        ReportCard.add(resetText);
        resetText.setBounds(40, 440, 430, 24);

        GoodPoints.setFont(new java.awt.Font("Timotheos", 0, 18)); // NOI18N
        GoodPoints.setForeground(new java.awt.Color(0, 204, 0));
        GoodPoints.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GoodPoints.setText("Great Job !! Keep up ");
        GoodPoints.setVisible(false);
        ReportCard.add(GoodPoints);
        GoodPoints.setBounds(64, 434, 380, 30);

        Again.setBackground(new java.awt.Color(189, 141, 125));
        Again.setFont(new java.awt.Font("Timotheos", 0, 14)); // NOI18N
        Again.setForeground(new java.awt.Color(255, 255, 255));
        Again.setText("Repeat Level");
        Again.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgainActionPerformed(evt);
            }
        });
        ReportCard.add(Again);
        Again.setBounds(90, 500, 130, 40);

        Exit1.setBackground(new java.awt.Color(236, 236, 236));
        Exit1.setFont(new java.awt.Font("Timotheos", 0, 36)); // NOI18N
        Exit1.setForeground(new java.awt.Color(153, 0, 0));
        Exit1.setText("X");
        Exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit1ActionPerformed(evt);
            }
        });
        ReportCard.add(Exit1);
        Exit1.setBounds(470, 10, 60, 50);

        ResetPoints.setBackground(new java.awt.Color(189, 141, 125));
        ResetPoints.setFont(new java.awt.Font("Timotheos", 0, 14)); // NOI18N
        ResetPoints.setText("Reset Points");
        ResetPoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetPointsActionPerformed(evt);
            }
        });
        ReportCard.add(ResetPoints);
        ResetPoints.setBounds(290, 500, 130, 40);

        background7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thinkfastwithjava/sea_of_clouds-wallpaper-960x600.jpg"))); // NOI18N
        ReportCard.add(background7);
        background7.setBounds(0, 0, 540, 570);

        cardsPanel2.add(ReportCard, "NextQuestion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardsPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardsPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 
     * @param game close operation 
     */
    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        ExitFrame exit = new  ExitFrame();
        exit.setVisible(true);
    }//GEN-LAST:event_ExitActionPerformed
      /**
       * @param evt 
       */
    private void Answer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Answer1ActionPerformed
        
    }//GEN-LAST:event_Answer1ActionPerformed

    
    int count = 0 ;//question count
    int bcount;
    /**
     * 
     * @param next question operation 
     */
    private void NextQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextQuestionActionPerformed
      
        if(questions != null){
         bcount = q.gameScore(questions.get(count).Solution1,questions.get(count).Solution2,Answer1.getText(),Answer2.getText());
             System.out.println("ans"+count);
             count = count+1;
             System.out.println(count+ " size "+questions.size());
           if(count == questions.size() || (m == 0 && s == 0)){
               String next = "NextQuestion";
              CardLayout layout = (CardLayout)this.cardsPanel2.getLayout();
              layout.show(cardsPanel2, next);
              boolean nextLevel= JavaGameForm.player.PlayerScore(Integer.parseInt(score.getText()));
              if(JavaGameForm.player.levels.levelNum==4){
              ResetPoints.setVisible(true);
              NextLavel.setVisible(false);
              Again.setVisible(false);
              PlayerScore.setText(this.score.getText());
              levelNumLoad.setText("");
              playerName.setText(WelcomePlayer.PlayerName.getText());
              NextQuestion.setVisible(false);
              }  
              else{
                 NextLavel.setEnabled(nextLevel);
                 resetText.setVisible(!(nextLevel));
                 Again.setVisible(!(nextLevel));
                 GoodPoints.setVisible(nextLevel);
                 ResetPoints.setVisible(false);
                 System.out.print(nextLevel);}
                                
              PlayerScore.setText(this.score.getText());
              levelNumLoad.setText(this.LevelNum.getText());
              playerName.setText(WelcomePlayer.PlayerName.getText());
              NextQuestion.setEnabled(false);
               }
          else{ 
             Image im = getToolkit().createImage(questions.get(count).QuestionContent);
             System.out.println("img count"+count);
             Image newImage = im.getScaledInstance(Question.getWidth(), Question.getHeight(), Image.SCALE_SMOOTH);
             ImageIcon ic = new ImageIcon(newImage);
             Question.setIcon(ic);
             score.setText(""+ bcount);
             Answer1.setText("");
             Answer2.setText("");
           } }
     
    }//GEN-LAST:event_NextQuestionActionPerformed
      /**
       * 
       * @param game pause 
       */
    private void PauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PauseActionPerformed
        timer.stop();
        Resume.setVisible(true);
        Pause.setVisible(false);
        Answer1.setEnabled(false);
        Answer2.setEnabled(false);
        NextQuestion.setEnabled(false);
    }//GEN-LAST:event_PauseActionPerformed
        /**
         * 
         * @param game resume 
         */
    private void ResumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResumeActionPerformed
        timer.start();
        Resume.setVisible(false);
        Pause.setVisible(true);
        Answer1.setEnabled(true);
        Answer2.setEnabled(true);
        NextQuestion.setEnabled(true);
    }//GEN-LAST:event_ResumeActionPerformed
         /**
          * 
          * @param next level operation 
          */
    private void NextLavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextLavelActionPerformed
         // TODO add your handling code here:
           WelcomePlayer welcome = new WelcomePlayer();
           welcome.setVisible(true);
           welcome.ReallyNew.setVisible(false);
           welcome.PlayerName.setText(JavaGameForm.player.playetName);
           welcome.DeleteRecord.setVisible(true);
           player = PlayerInfo.loadPlayerInfo(JavaGameForm.player.playetName); 
           WelcomePlayer.ExistPlayerInfo1.setText(player.printScore());//your score 
           WelcomePlayer.ExistPlayerInfo2.setText(player.printLevelNum());//you are at level
           close();
    }//GEN-LAST:event_NextLavelActionPerformed
    /**
     * 
     * @param repeat level operation 
     */   
    private void AgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgainActionPerformed
                     
           WelcomePlayer welcome = new WelcomePlayer();
           welcome.setVisible(true);
           welcome.ReallyNew.setVisible(false);
           welcome.PlayerName.setText(JavaGameForm.player.playetName);
           welcome.DeleteRecord.setVisible(true);
           player = PlayerInfo.loadPlayerInfo(JavaGameForm.player.playetName); 
           WelcomePlayer.ExistPlayerInfo1.setText(player.printScore());//your score 
           WelcomePlayer.ExistPlayerInfo2.setText(player.printLevelNum());//you are at level
           close();
                    
    }//GEN-LAST:event_AgainActionPerformed
     /**
      * 
      * @param game close operation 
      */
    private void Exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit1ActionPerformed
        ExitFrame exit = new  ExitFrame();
        exit.setVisible(true); 
    }//GEN-LAST:event_Exit1ActionPerformed
    /**
     * 
     * @param points reset when finished all levels 
     */
    private void ResetPointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetPointsActionPerformed
        JavaGameForm.player.updatePlayerInfo(0, 0, 0, 0, 1);
        WelcomePlayer welcome = new WelcomePlayer();
           welcome.setVisible(true);
           welcome.ReallyNew.setVisible(false);
           welcome.PlayerName.setText(JavaGameForm.player.playetName);
           welcome.DeleteRecord.setVisible(true);
           player = PlayerInfo.loadPlayerInfo(JavaGameForm.player.playetName); 
           WelcomePlayer.ExistPlayerInfo1.setText(player.printScore());//your score 
           WelcomePlayer.ExistPlayerInfo2.setText(player.printLevelNum());//you are at level
           close();// TODO add your handling code here:
    }//GEN-LAST:event_ResetPointsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Again;
    protected javax.swing.JTextField Answer1;
    protected javax.swing.JTextField Answer2;
    protected javax.swing.JLabel AnswerPlace;
    protected javax.swing.JLabel AnswerPlace2;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Exit1;
    private javax.swing.JLabel GoodPoints;
    private javax.swing.JLabel Level;
    private javax.swing.JLabel LevelFinished;
    protected javax.swing.JLabel LevelNum;
    private javax.swing.JButton NextLavel;
    protected javax.swing.JButton NextQuestion;
    private javax.swing.JButton Pause;
    private javax.swing.JLabel PlayerScore;
    protected javax.swing.JLabel Question;
    private javax.swing.JPanel ReportCard;
    private javax.swing.JButton ResetPoints;
    private javax.swing.JButton Resume;
    private javax.swing.JLabel Seconds;
    private javax.swing.JLabel Time;
    private javax.swing.JLabel TimeOut;
    private javax.swing.JPanel TimerAndLevelPanel;
    private javax.swing.JLabel background6;
    private javax.swing.JLabel background7;
    private javax.swing.JPanel cardsPanel2;
    private javax.swing.JLabel hourglassIcon;
    private javax.swing.JLabel levelNumLoad;
    private javax.swing.JLabel levelText;
    private javax.swing.JLabel minutes;
    private javax.swing.JLabel playerName;
    private javax.swing.JLabel resetText;
    protected javax.swing.JLabel score;
    private javax.swing.JLabel score1;
    private javax.swing.JLabel scoreLoad;
    private javax.swing.JLabel simicolon;
    // End of variables declaration//GEN-END:variables
}
