/*
 * This class allows the player himself or delete the disease play
 */
package thinkfastwithjava;

import java.awt.CardLayout;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import static thinkfastwithjava.JavaGameForm.player;

/**
 *
 * @author Bayan Mamun ID: 434023821 
 */
public class WelcomePlayer extends javax.swing.JFrame  {
    
    /**
     * Creates new form Levels
     */
    public WelcomePlayer() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    /**
     * game close operation
     */
    public void close(){
           WindowEvent winClosingEvent =  new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
           Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
       }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LevelsCard = new javax.swing.JPanel();
        WelcomingText = new javax.swing.JLabel();
        PlayerName = new javax.swing.JLabel();
        AreYouReady = new javax.swing.JLabel();
        LevelText = new javax.swing.JLabel();
        ExistPlayerInfo2 = new javax.swing.JLabel();
        ScoreText = new javax.swing.JLabel();
        AllLevelsFinished = new javax.swing.JLabel();
        Exit2 = new javax.swing.JButton();
        Help3 = new javax.swing.JButton();
        ReallyExist = new javax.swing.JButton();
        DeleteRecord = new javax.swing.JButton();
        Yes = new javax.swing.JButton();
        No = new javax.swing.JButton();
        ReallyNew = new javax.swing.JButton();
        ResetPoints = new javax.swing.JButton();
        AreYouSure = new javax.swing.JLabel();
        background6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Welcome");
        setResizable(false);
        setSize(new java.awt.Dimension(540, 600));

        LevelsCard.setLayout(null);

        WelcomingText.setFont(new java.awt.Font("Timotheos", 0, 60)); // NOI18N
        WelcomingText.setForeground(new java.awt.Color(51, 51, 51));
        WelcomingText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomingText.setText("Welcome ");
        LevelsCard.add(WelcomingText);
        WelcomingText.setBounds(30, 50, 480, 150);

        PlayerName.setFont(new java.awt.Font("Timotheos", 0, 60)); // NOI18N
        PlayerName.setForeground(new java.awt.Color(196, 0, 0));
        PlayerName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LevelsCard.add(PlayerName);
        PlayerName.setBounds(50, 180, 430, 100);

        AreYouReady.setFont(new java.awt.Font("Timotheos", 0, 36)); // NOI18N
        AreYouReady.setForeground(new java.awt.Color(102, 91, 84));
        AreYouReady.setText("Are You Ready to play !!?");
        LevelsCard.add(AreYouReady);
        AreYouReady.setBounds(60, 340, 440, 51);

        ExistPlayerInfo1.setFont(new java.awt.Font("Timotheos", 0, 18)); // NOI18N
        ExistPlayerInfo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ExistPlayerInfo1.setVisible(true);
        LevelsCard.add(ExistPlayerInfo1);
        ExistPlayerInfo1.setBounds(150, 290, 110, 40);

        LevelText.setFont(new java.awt.Font("Timotheos", 0, 24)); // NOI18N
        LevelText.setForeground(new java.awt.Color(153, 0, 0));
        LevelText.setText("Level: ");
        LevelsCard.add(LevelText);
        LevelText.setBounds(310, 290, 90, 40);

        ExistPlayerInfo2.setFont(new java.awt.Font("Timotheos", 0, 18)); // NOI18N
        ExistPlayerInfo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ExistPlayerInfo1.setVisible(true);
        LevelsCard.add(ExistPlayerInfo2);
        ExistPlayerInfo2.setBounds(390, 290, 90, 40);

        ScoreText.setFont(new java.awt.Font("Timotheos", 0, 24)); // NOI18N
        ScoreText.setForeground(new java.awt.Color(153, 0, 0));
        ScoreText.setText("Score: ");
        LevelsCard.add(ScoreText);
        ScoreText.setBounds(80, 290, 90, 40);

        AllLevelsFinished.setFont(new java.awt.Font("Timotheos", 0, 36)); // NOI18N
        AllLevelsFinished.setForeground(new java.awt.Color(153, 0, 0));
        AllLevelsFinished.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AllLevelsFinished.setText("You Have Finished All Levels");
        AllLevelsFinished.setVisible(false);
        LevelsCard.add(AllLevelsFinished);
        AllLevelsFinished.setBounds(10, 290, 520, 40);

        Exit2.setBackground(new java.awt.Color(236, 236, 236));
        Exit2.setFont(new java.awt.Font("Timotheos", 0, 36)); // NOI18N
        Exit2.setForeground(new java.awt.Color(153, 0, 0));
        Exit2.setText("X");
        Exit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit2ActionPerformed(evt);
            }
        });
        LevelsCard.add(Exit2);
        Exit2.setBounds(430, 20, 60, 50);

        Help3.setBackground(new java.awt.Color(236, 236, 236));
        Help3.setFont(new java.awt.Font("Timotheos", 0, 36)); // NOI18N
        Help3.setForeground(new java.awt.Color(153, 0, 0));
        Help3.setText("?");
        Help3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Help3ActionPerformed(evt);
            }
        });
        LevelsCard.add(Help3);
        Help3.setBounds(350, 20, 70, 50);

        ReallyExist.setBackground(new java.awt.Color(189, 141, 125));
        ReallyExist.setFont(new java.awt.Font("Timotheos", 0, 18)); // NOI18N
        ReallyExist.setForeground(new java.awt.Color(255, 255, 255));
        ReallyExist.setText("Continue");
        ReallyExist.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ReallyExist.setVerifyInputWhenFocusTarget(false);
        ReallyExist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReallyExistActionPerformed(evt);
            }
        });
        LevelsCard.add(ReallyExist);
        ReallyExist.setBounds(60, 420, 190, 50);

        DeleteRecord.setBackground(new java.awt.Color(189, 141, 125));
        DeleteRecord.setFont(new java.awt.Font("Timotheos", 0, 18)); // NOI18N
        DeleteRecord.setForeground(new java.awt.Color(255, 255, 255));
        DeleteRecord.setText("Delete my Record");
        DeleteRecord.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DeleteRecord.setVerifyInputWhenFocusTarget(false);
        DeleteRecord.setVisible(false);
        DeleteRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteRecordActionPerformed(evt);
            }
        });
        LevelsCard.add(DeleteRecord);
        DeleteRecord.setBounds(280, 420, 190, 50);

        Yes.setBackground(new java.awt.Color(189, 141, 125));
        Yes.setFont(new java.awt.Font("Timotheos", 0, 18)); // NOI18N
        Yes.setForeground(new java.awt.Color(255, 255, 255));
        Yes.setText("Yes");
        Yes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Yes.setVerifyInputWhenFocusTarget(false);
        Yes.setVisible(false);
        Yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesActionPerformed(evt);
            }
        });
        LevelsCard.add(Yes);
        Yes.setBounds(140, 500, 120, 40);

        No.setBackground(new java.awt.Color(189, 141, 125));
        No.setFont(new java.awt.Font("Timotheos", 0, 18)); // NOI18N
        No.setForeground(new java.awt.Color(255, 255, 255));
        No.setText("No");
        No.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        No.setVerifyInputWhenFocusTarget(false);
        No.setVisible(false);
        No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoActionPerformed(evt);
            }
        });
        LevelsCard.add(No);
        No.setBounds(270, 500, 120, 40);

        ReallyNew.setBackground(new java.awt.Color(189, 141, 125));
        ReallyNew.setFont(new java.awt.Font("Timotheos", 0, 24)); // NOI18N
        ReallyNew.setForeground(new java.awt.Color(255, 255, 255));
        ReallyNew.setText("I'm always ready !!");
        ReallyNew.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ReallyNew.setVerifyInputWhenFocusTarget(false);
        ReallyNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReallyNewActionPerformed(evt);
            }
        });
        LevelsCard.add(ReallyNew);
        ReallyNew.setBounds(120, 420, 270, 50);

        ResetPoints.setBackground(new java.awt.Color(189, 141, 125));
        ResetPoints.setFont(new java.awt.Font("Timotheos", 0, 18)); // NOI18N
        ResetPoints.setForeground(new java.awt.Color(255, 255, 255));
        ResetPoints.setText("Reset My Points");
        ResetPoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetPointsActionPerformed(evt);
            }
        });
        LevelsCard.add(ResetPoints);
        ResetPoints.setBounds(60, 420, 190, 50);

        AreYouSure.setFont(new java.awt.Font("Timotheos", 0, 18)); // NOI18N
        AreYouSure.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AreYouSure.setText("Are you sure ? Your name will be deleted");
        AreYouSure.setVisible(false);
        LevelsCard.add(AreYouSure);
        AreYouSure.setBounds(54, 464, 440, 40);

        background6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thinkfastwithjava/sea_of_clouds-wallpaper-960x600.jpg"))); // NOI18N
        LevelsCard.add(background6);
        background6.setBounds(0, 0, 600, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(LevelsCard, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(LevelsCard, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 
     * @param game close operation 
     */
    private void Exit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit2ActionPerformed
        ExitFrame exit = new  ExitFrame();
        exit.setVisible(true);
        
    }//GEN-LAST:event_Exit2ActionPerformed

    /**
     * 
     * @param tutorial 
     */
    private void Help3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Help3ActionPerformed
        JavaGameFrame2 frame2 = new JavaGameFrame2();
        frame2.setVisible(true);
        try {
              player.readInFile();
          } catch (IOException ex) {
              Logger.getLogger(JavaGameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_Help3ActionPerformed
      /**
       * 
       * @param now really start game for exist player
       */
    private void ReallyExistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReallyExistActionPerformed
        
        NewJFrame f = new NewJFrame();
        f.setVisible(true);
        f.timer.start(); 
        if(JavaGameForm.player.levels.levelNum==3){
         f.AnswerPlace.setVisible(false);
         f.AnswerPlace2.setVisible(true);
        System.out.println(false);
        }
         else{ 
          f.AnswerPlace2.setVisible(false);
          }
        Image im = getToolkit().createImage(f.questions.get(0).QuestionContent);
        Image newImage = im.getScaledInstance(f.Question.getWidth(), f.Question.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon ic = new ImageIcon(newImage);
        f.Question.setIcon(ic);
        
        close();           
        
            f.score.setText("0");//your score 
            f.LevelNum.setText(""+JavaGameForm.player.levels.levelNum);//you are at level}
            System.out.println("past record activated");

    }//GEN-LAST:event_ReallyExistActionPerformed
 
   /**
    * 
    * @param now really start game for new player 
    */
    private void ReallyNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReallyNewActionPerformed
           NewJFrame f = new NewJFrame();
           f.setVisible(true);
           f.timer.start();
           
        Image im = getToolkit().createImage(f.questions.get(0).QuestionContent);
        Image newImage = im.getScaledInstance(f.Question.getWidth(), f.Question.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon ic = new ImageIcon(newImage);
           f.Question.setIcon(ic);
           close();  
           f.AnswerPlace2.setVisible(false);
           f.AnswerPlace.setVisible(true);
        
           f.score.setText("0");//your score 
           f.LevelNum.setText(""+JavaGameForm.player.levels.levelNum);//you are at level}
           System.out.println("new record activated");               

    }//GEN-LAST:event_ReallyNewActionPerformed
           /**
            * 
            * @param delete whole record with primary key for existing player 
            */
    private void DeleteRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteRecordActionPerformed
        ReallyExist.setEnabled(false);
        Yes.setVisible(true);
        No.setVisible(true);
        AreYouSure.setVisible(true);
        
    }//GEN-LAST:event_DeleteRecordActionPerformed
         
    /**
     * 
     * @param delete confirmation 
     */
    private void YesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesActionPerformed

        JavaGameForm.player.deleatPlayerInfo(JavaGameForm.player.playetName);
        JavaGameForm f = new JavaGameForm();
        PlayerName.setText("Your Record is deleted");
        ScoreText.setVisible(false);
        LevelText.setVisible(false);
        ExistPlayerInfo1.setVisible(false);
        ExistPlayerInfo2.setVisible(false);
          f.setVisible(true);
          close();
          
    }//GEN-LAST:event_YesActionPerformed
     /**
      * 
      * @param no delete 
      */
    private void NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoActionPerformed
        ReallyExist.setEnabled(true);
        Yes.setVisible(false);
        No.setVisible(false);
        AreYouSure.setVisible(false);
        
    }//GEN-LAST:event_NoActionPerformed
      /**
       * 
       * @param update player record to 0 
       */
    private void ResetPointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetPointsActionPerformed
        JavaGameForm.player.updatePlayerInfo(0, 0, 0, 0, 1);
        WelcomePlayer welcome = new WelcomePlayer();
           welcome.setVisible(true);
           welcome.ReallyExist.setVisible(true);
           welcome.ReallyNew.setVisible(false);
           welcome.PlayerName.setText(JavaGameForm.player.playetName);
           welcome.DeleteRecord.setVisible(true);
           player = PlayerInfo.loadPlayerInfo(JavaGameForm.player.playetName); 
           WelcomePlayer.ExistPlayerInfo1.setText(player.printScore());//your score 
           WelcomePlayer.ExistPlayerInfo2.setText(player.printLevelNum());//you are at level
           close(); // TODO add your handling code here:
    }//GEN-LAST:event_ResetPointsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomePlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomePlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomePlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomePlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomePlayer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JLabel AllLevelsFinished;
    protected javax.swing.JLabel AreYouReady;
    private javax.swing.JLabel AreYouSure;
    protected javax.swing.JButton DeleteRecord;
    public static final javax.swing.JLabel ExistPlayerInfo1 = new javax.swing.JLabel();
    protected static javax.swing.JLabel ExistPlayerInfo2;
    private javax.swing.JButton Exit2;
    private javax.swing.JButton Help3;
    protected javax.swing.JLabel LevelText;
    private javax.swing.JPanel LevelsCard;
    protected javax.swing.JButton No;
    public static javax.swing.JLabel PlayerName;
    protected javax.swing.JButton ReallyExist;
    protected javax.swing.JButton ReallyNew;
    protected javax.swing.JButton ResetPoints;
    protected javax.swing.JLabel ScoreText;
    private javax.swing.JLabel WelcomingText;
    protected javax.swing.JButton Yes;
    private javax.swing.JLabel background6;
    // End of variables declaration//GEN-END:variables
}
